//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThpKTGiuaKi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thpSinhVien
    {
        public string ThpMaSV { get; set; }
        public string ThpHoSV { get; set; }
        public string ThpTenSV { get; set; }
        public Nullable<System.DateTime> ThpNgaySinh { get; set; }
        public Nullable<bool> ThpPhai { get; set; }
        public string ThpPhone { get; set; }
        public string ThpEmail { get; set; }
        public string ThpMaKH { get; set; }
    
        public virtual thpKhoa thpKhoa { get; set; }
    }
}
